Add an example of working/not working code for cluster actor
Tochemey/goakt pull request #456
Opened 2024-09-03 12:44 UTC by webfrank

Just a note on Actor instantiation when using clustering feature.

2024-09-03 14:58 UTC, Tochemey commented
@webfrank I think this is sufficient enough https://github.com/Tochemey/goakt?tab=readme-ov-file#redeployment

2024-09-03 19:16 UTC, webfrank commented
> @webfrank I think this is sufficient enough https://github.com/Tochemey/goakt?tab=readme-ov-file#redeployment

On first read it was not clear. Probably adding the example would be clearer.

2024-09-04 22:27 UTC, Tochemey requested changes

2024-09-04 22:27 UTC, Tochemey commented on README.md
> -- [Design Principles](#design-principles)
It seems the formatting is wrong. Also I am using tab of 2 for indentation. I think I need to state that in the contribution doc. :)

2024-09-04 22:27 UTC, Tochemey commented on README.md
> +When levereging cluster re-balancing, leaving the supervisor to re-instatiate an actor in case of node fail, actors should be created as plain structs without parameters. This is required because whe
I don't think this note should be here. It should be rather under `Redeployment` section. Also there is no concept of supervisor in the clustering feature. Once cluster mode is enabled, actors are redeployed whenever the cluster topology changes and the members quorum respected.

2024-09-06 06:32 UTC, Tochemey commented
@webfrank I have updated the doc in that regard. I honestly don't think we should add an example for that.

2024-09-08 12:07 UTC, closed without merging

2024-09-08 12:07 UTC, Tochemey commented
I closed this PR for lack of activities